config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get "home/top"=>"homes#top"
  get "home/about"=>"homes#about"
  root to: "homes#top"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  #フォロー一覧へのルート
  get 'users/:id/followings' => 'relationships#followings', as: 'followings'
  get 'users/:id/followers' => 'relationships#followers', as: 'followers'

  #検索機能
  get "search" => "searches#search"
  get "search_tag"=>"books#search_tag"

  #コメントのエラーメッセージが出た画面でリロードした際のエラー回避
  get "books/:id/book_comments" => "book_comments#top"

  #カテゴリ分け
  get 'books/text' => 'books#text'
  get 'books/novel' => 'books#novel'
  get 'books/comic' => 'books#comic'
  get 'books/others' => 'books#others'

  #ゲストユーザーログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment,presence:true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def top
    redirect_to request.referer
  end

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
    else
      @user = @book.user
      render :error
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    @book = Book.find(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user.id) do %>
          <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <% if book_comment.user == current_user %>
        <td>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger", remote: true %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/_count.html.erb
コメント数:<%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<div>
  <%= form_with model: [book, book_comment], local: false do |f| %>
    <%= f.text_area :comment, class: "col-12" %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$("#comment_area").html("<%= j(render "book_comments/comments", book: @book, book_comment: @book_comment) %>");
$("#comment_count").html("<%= j(render "book_comments/count",book: @book) %>");
$("textarea").val("");
$("#comment_error").html("<%= j(render"layouts/errors", obj: @book_comment) %>");

app/views/book_comments/destroy.js.erb
$("#comment_area").html("<%= j(render "book_comments/comments", book: @book) %>");
$("#comment_count").html("<%= j(render "book_comments/count",book: @book) %>");

app/views/book_comments/error.js.erb
$("#comment_error").html("<%= j(render"layouts/errors", obj: @book_comment) %>");