config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get "home/top"=>"homes#top"
  get "home/about"=>"homes#about"
  root to: "homes#top"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  #フォロー一覧へのルート
  get 'users/:id/followings' => 'relationships#followings', as: 'followings'
  get 'users/:id/followers' => 'relationships#followers', as: 'followers'

  #検索機能
  get "search" => "searches#search"
  get "search_tag"=>"books#search_tag"

  #コメントのエラーメッセージが出た画面でリロードした際のエラー回避
  get "books/:id/book_comments" => "book_comments#top"

  #カテゴリ分け
  get 'books/text' => 'books#text'
  get 'books/novel' => 'books#novel'
  get 'books/comic' => 'books#comic'
  get 'books/others' => 'books#others'

  #ゲストユーザーログイン機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :booktags,dependent: :destroy
  has_many :tags,through: :booktags

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  #検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
  
  def save_tag(sent_tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - sent_tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = sent_tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete　Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      new_booktag = Tag.find_or_create_by(name: new)
      self.tags << new_booktag
   end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_tag = @book.tags
  end

  def index
    @books = Book.all
    @book = Book.new
    @tag_list=Tag.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:name].split(',')
    if @book.save
      @book.save_tag(tag_list)
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @tag_list = @book.tags.pluck(:name).join(',')
    if @book.user !=current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    tag_list = params[:book][:name].split(',')
    if @book.update(book_params)
      # このpost_idに紐づいていたタグを@oldに入れる
      old_tags = Booktag.where(book_id: @book.id)
      # それらを取り出し、消す。消し終わる
      old_tags.each do |tag|
        tag.delete
      end
      @book.save_tag(tag_list)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def text
    @books = Book.all
  end

  def novel
    @books = Book.all
  end

  def comic
    @books = Book.all
  end

  def others
    @books = Book.all
  end

  def search_tag
    @book = Book.new
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @books = @tag.books
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:star,:category)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,　local:true do |f| %>
  <%= render 'layouts/errors', obj: book %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, [["テキスト", "text"], ["小説", "novel"], ["漫画", "comic"], ["その他", "others"]], include_blank: "カテゴリ" %>
  </div>
  <div>
    <label>タグ</label>
    <%= f.text_field :name %>
  </div>

  <% if request.path.include?("edit") %>
    <div class="form-group row">
    <label class="col-md-3 col-form-label"> Rate</label>
    <span id="star<%= book.id %>"></span>
    </div>

    <script>
      $('#star<%= book.id %>').empty();
      $('#star<%= book.id %>').raty({
        size:36,
        starOff: '<%= asset_path('star-off.png') %>',
        starOn: '<%= asset_path('star-on.png') %>',
        readOnly: true,
        score: <%= book.star %>,
        half: false,
      });
    </script>

  <% else %>
    <div class="form-group row">
      <%= f.label :star, 'Rate', class: 'col-md-3 col-form-label' %>
      <span id="star"><%= f.hidden_field :star, id: :review_star %></span>
    </div>

  <script>
    $('#star').empty();
    $('#star').raty({
      size:36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      scoreName: 'book[star]',
      half: false,
    });
  </script>

  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>

<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
        <td id="comment_count"><%= render 'book_comments/count', book: book %></td>
        <td><%= book.tags.map(&:name).join(', ') %></td>
        <td id="star<%= book.id %>"></td>
        <script>
          $('#star<%= book.id %>').empty();
          $('#star<%= book.id %>').raty({
            size:36,
            starOff: '<%= asset_path('star-off.png') %>',
            starOn: '<%= asset_path('star-on.png') %>',
            readOnly: true,
            score: <%= book.star %>,
            half: false,
          });
        </script>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/comic.html.erb
<div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <% if t.category == comic %>
      <%= render 'index', books: @books%>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <!--タグリスト-->
      <div>
        <% @tag_list.each do |list|%>
          <%=list.name %>
          <%="(#{list.books.count})" %>
        <% end %>
      </div>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/novel.html.erb
<div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <% if t.category == novel %>
      <%= render 'index', books: @books%>
    <% end %>
</div>

app/views/books/others.html.erb
<div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <% if @books.category == others %>
      <%= render 'index', books: @books%>
    <% end %>
</div>

app/views/books/search_tag.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2><%= @tag.name %>の検索結果</h2>
      <!--タグリスト-->
      <div class="d-flex">
        <% @tag_list.each do |list|%>
          <div class="ml-2">
            <%= link_to search_tag_path(tag_id: list.id) do %>
              <%=list.name %>
              (<%= list.books.count %>)
            <% end %>
          </div>
        <% end %>
      </div>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite_btn_<%= @book.id %>"><%= render 'favorites/favorite', book: @book %></td>
          <td id="comment_count"><%= render 'book_comments/count', book: @book %></td>
          <td id="star<%= @book.id %>"></td>
          <td>
            <% @book_tag.each do |tag| %>
              <%= tag.name %>
            <% end %>
          </td>
          <script>
            $('#star<%= @book.id %>').empty();
            $('#star<%= @book.id %>').raty({
              size:36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn: '<%= asset_path('star-on.png') %>',
              readOnly: true,
              score: <%= @book.star %>,
              half: false,
            });
          </script>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <span id="comment_area"><%= render 'book_comments/comments', book: @book, book_comment: @book_comment %></span>
      <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
      <span id="comment_error"><%= render 'layouts/errors', obj: @book_comment %></span>
    </div>
  </div>
</div>

app/views/books/text.html.erb
<div class='col-md-8 offset-md-1'>
    <h2>Books</h2>
    <% if @books.category == text %>
      <%= render 'index', books: @books%>
    <% end %>
</div>